import React from "react";
import {Button, ButtonGroup, Grid, Flex} from "@chakra-ui/react"
import {ChakraProvider} from "@chakra-ui/react"

function App() {
    return (
        <ChakraProvider>
            <Flex direction="column" align="center" justify="space-between" width="80%" height="100%"
                  backgroundColor="#ffd803" mx="auto" py="2%">
                <Grid templateColumns="repeat(9, 1fr)" gap={1} w="800px"
                >

                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                </Grid>
            </Flex>
        </ChakraProvider>
    );
}

export default App;
