import React, { useState } from "react";
import {Button, ButtonGroup, Grid, Flex} from "@chakra-ui/react"
import {ChakraProvider} from "@chakra-ui/react"
import {useState} from "react/cjs/react.production.min";

function App() {
    
    const [table, setTable] = useState([1,2,3,4,5,6,7,8,9,10,11,12])
    
    
    return (
        <ChakraProvider>
            <Flex direction="column" align="center" justify="space-between" width="80%" height="full"
                  backgroundColor="#ffd803" mx="auto" py="1%">
                <Grid templateColumns="repeat(9, 1fr)" gap="5%" w="800px" h="100%"
                >

                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"

                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                        // isActive="false"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button><Button
                    size="md"
                    height="48px"
                    width="48px"
                    border="2px"
                    borderColor="green.500"
                >
                    1
                </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        1
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                    <Button
                        size="md"
                        height="48px"
                        width="48px"
                        border="2px"
                        borderColor="green.500"
                    >
                        2
                    </Button>
                </Grid>
            </Flex>
        </ChakraProvider>
    );
}

export default App;
